services:
  backend:
    image: mybackend
    build: back-end/
    container_name: mybackend2
    ports:
      - "5002:5000"
    networks:
      - mynetwork

  frontend:
    image: myfrontend
    build: .
    container_name: myfrontend
    ports:
      - "8081:80"
    networks:
      - mynetwork
    depends_on:
      - backend

  postgres:
    image: postgres
    container_name: mypostgres2
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
